### ISSUE TITLE
Question / Issue with Details Optional Class

### ISSUE THREAD

**Issue by dgmorrisjr** [facelessuser/pymdown-extensions#105]
Hi @facelessuser!  pymdown-extensions are great!   Love using them with the Material theme for MKDocs.   I have a question for you though...could just be something i'm doing wrong.

I'm trying to use the Details extension, and in general it works.   However, I'm try to add styling per your examples in documentation.   Here is the markdown I'm using:

```
## Admonitions

!!! note "this is a note"
    In this admonition the node class works

## Hidden Details

??? note "What is "Hidden Details?""

    Creates collapsible elements that hide their content.

    In this "hidden details", the note calss doesn't work.

```

And here is the resulting content:
![image](https://user-images.githubusercontent.com/12668108/27764784-4057ba64-5e70-11e7-800d-87063ce5b471.png)

I'm currently working with these pages on OS X 10.12.5, using:
```
mkdocs (0.16.3)
mkdocs-extensions (0.1.2)
mkdocs-material (1.7.4)
Pygments (2.2.0)
pymdown-extensions (3.5)
```

I've tried viewing the pages in chrome, firefox, and safari, and the all result in the same thing.

**Comment by facelessuser** [comment]
I can assure you it does work as my documentation, which uses details, uses this plugin, but...

The material styling you see in my documentation is because I'm adding additional styling to the theme.  I don't really provide the style I'm using in the docs; I just provide the basics to get working details and mention that you **can** style it as you wish.  Pymdown-extensions isn't a theme, so I don't really provide that as you may style it differently for different documents.

So, is the real question: where's the special sauce to get the styling I'm using?  If so, here it is: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_details.scss#L56.  It's in SCSS, so you'd have to convert it to CSS.  You could try and dig the CSS out of the compressed, compiled CSS here if you have something to uncompress it: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/theme/extra-6068b97e47.css.

**Comment by facelessuser** [comment]
I went ahead and ran it through the converter: here is the JS and CSS I use (I should probably write the SCSS in a way that generates more compact CSS...).

https://gist.github.com/facelessuser/230e10cd0483a9fea8a705cde51b8c95.

**Comment by facelessuser** [comment]
Updated gist above with more a more compact generated CSS!  That should cover everything.  Let me know if that gets it all working for you.

**Comment by dgmorrisjr** [comment]
Great! Thanks so much!   Okay... I see that the "optional class" is if we add our own CSS and then we reference that class.   Sorry that went past me the first time around.   I'll take a look at what you've provided and give it a try.   Appreciate the help!

**Comment by facelessuser** [comment]
> I see that the "optional class" is if we add our own CSS and then we reference that class

Yeah, maybe I need to be more explicit about that tidbit of info.  I should probably update that for clarity.

**Comment by dgmorrisjr** [comment]
It worked great!!!   Thanks again for the help!

**Comment by dgmorrisjr** [comment]
If you do update, one option could be to link back to the Material Theme's documentation regarding adding [customization](http://squidfunk.github.io/mkdocs-material/customization/).  I personally found that section more useful than the for this scenario than the documentation from the MkDocs section of [Styling Your Docs](http://www.mkdocs.org/user-guide/styling-your-docs/).  

Again - love the extensions - They are great!

**Comment by facelessuser** [comment]
Glad you got it working.

> Again - love the extensions - They are great!

Thanks! Glad people find it useful :).
