### ISSUE TITLE
Pymdown main documentation 404 page is not stylized and dead links

### ISSUE THREAD

**Issue by Timber232** [facelessuser/pymdown-extensions#106]
Just wanted to let you know that your 404 is not stylized :

![image](https://user-images.githubusercontent.com/627637/28691806-3c6f4a76-72ec-11e7-9a82-5c04d8c4f96f.png)

And also, on your ["Extensions -> Extra"](http://facelessuser.github.io/pymdown-extensions/extensions/extra/) page, you've got a couple of dead links in the Extensions table (see highlighted on the screenshot below):

![image](https://user-images.githubusercontent.com/627637/28691928-92e2ceb4-72ec-11e7-932d-4bef2153a977.png)

**Comment by facelessuser** [comment]
Thanks for pointing this out.  I'll take a look when I get a chance.

**Comment by facelessuser** [comment]
Links fixed.  404 page seems to work locally, but it is broken on GitHub pages.  Sigh...most likely it is a Jinja override issue because I override base.html...

**Comment by facelessuser** [comment]
site_url must be specified for 404 to work.

**Comment by Timber232** [comment]
Awesome! Seems like you got it.

I found another :)

![image](https://user-images.githubusercontent.com/627637/28695576-ff252246-72fd-11e7-8500-4a8ea24d3dab.png)

The "Edit this page" buttons at the top right of the screen are also dead links.

**Comment by facelessuser** [comment]
Hmm...That should just work automatically...this might be a mkdocs bug.  It finds the files for building, but messes up the links.  I think when the urls are created, it uses the path in `pages`, and though it uses `docs_dir` to find the files, I don't think it uses it to generate the links.  Ughh.

It's probably because my document src are not at the root level.  I wonder if that is one of their requirements. If it is, I'm not a fan of that.  I keep both the source and the theme overrides all under docs, so I set `docs_dir` to `docs/src/markdown`.  Links are getting generated as just `docs/file`.

I'll have to dig deeper into that to understand why it's breaking unfortunately.

**Comment by facelessuser** [comment]
Figured it out.  Had to set `edit_uri` to `tree/master/docs/src/markdown`.

**Comment by facelessuser** [comment]
Thanks for pointing these out. Not sure how long they would've stayed broken without getting a heads up :slightly_smiling_face: .

**Comment by Timber232** [comment]
NP! Thanks for the fix :)
Love your work on PymDown btw!

**Comment by facelessuser** [comment]
Thanks!

**Comment by facelessuser** [comment]
Leaving open to remind myself to push new docs.
