### ISSUE TITLE
[How to question] Critic stand out CSS

### ISSUE THREAD

**Issue by jimenezk** [facelessuser/pymdown-extensions#1069]
Hello,
May I know where or how to place the CSS code in [this section](https://facelessuser.github.io/pymdown-extensions/extensions/critic/#css), to make the color stand out while having the `scheme: slate` enabled? I am not an expert programmer, but I get by... except this one :)

Also, may I suggest to make it a default when using `scheme: slate`?

Kevin

**Comment by facelessuser** [comment]
When you say `scheme: slate` are you using Material for MkDocs? If so, the CSS should already be in there.

**Comment by jimenezk** [comment]
Material for MkDocs correct. When I use the slate scheme, highlighting text enclosed with either `==text==` or `{==text==}`, it doesn't show yellow, like it does in your site, it actually looks gray-ish. Check this out:

![image](https://user-images.githubusercontent.com/25873527/91484610-c0f7e080-e866-11ea-87a6-8739a95e9bef.png)

The first line I used `==text==` and `{==text==}` in the second.

**Comment by facelessuser** [comment]
Mine is a big custom:

![theme](https://user-images.githubusercontent.com/1055125/91489255-c147aa00-e86d-11ea-8aba-71d2a48d041b.gif)

In order to change, you just need to change the CSS variable:

![adjust](https://user-images.githubusercontent.com/1055125/91489748-898d3200-e86e-11ea-8ab9-6506d6818802.gif)

I don't normally have time to help people with custom stuff, but that should give you enough to figure things out.

You just need a little custom CSS and add it via `extra_css` in your `mkdocs.yml`.

I will close this issue as it is really out of scope and the question has been answered.

@gir-bot lgtm
@gir-bot add T: support

**Comment by jimenezk** [comment]
Understood. Thanks gentleman.
