### ISSUE TITLE
Improve accessibility on the Tasklist extension

### ISSUE THREAD

**Issue by fabianpiau** [facelessuser/pymdown-extensions#1109]
I was running a Lighthouse check on our website and realize this accessibility issue, I am using the 
[tasklist](https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/) extension.

The checkboxes do not have a label.

HTML (rendered + code):
![image](https://user-images.githubusercontent.com/6502229/94461043-7fce5580-01b1-11eb-9198-8d3b3a6254f5.png)

Lighthouse report:
![image](https://user-images.githubusercontent.com/6502229/94461334-e5224680-01b1-11eb-9153-55ad8314264f.png)

**Comment by facelessuser** [comment]
What are you expecting for a label?

**Comment by fabianpiau** [comment]
Maybe something like
```
label="task"
```
So it shows it's a task part of a checklist?

**Comment by facelessuser** [comment]
Besides satisfying the test, how is this helpful?

**Comment by fabianpiau** [comment]
Thanks to this extra info, I think the screen reader will give a bit more context to a blind person that this is a list and not a checkbox that can be ticked.

**Comment by facelessuser** [comment]
I mean, do you want a unique label for every task?

**Comment by fabianpiau** [comment]
It's not needed because it's not an ID, so it does not need to be unique, that said, you could help the reader to start from 1 and increment. So "Item 1", "Item 2", etc.

**Comment by facelessuser** [comment]
These aren't real inputs. I guess someone could use JavaScript to make them do something though...at the very least we can probably put a label like you suggest `task`. That is probably the most we'd do at this point.

**Comment by squidfunk** [comment]
Just as a hint - my testing shows that the text node that is rendered after the `label` could be moved inside the `label[class=task-list-control]` element without any styling issues – at least for the Material for MkDocs documentation which is widely used. Doing that has no visual effect:

<img width="1552" alt="Bildschirmfoto 2020-12-03 um 09 42 27" src="https://user-images.githubusercontent.com/932156/100985149-e8d49f80-354b-11eb-9a1f-e51d95fd308f.png">

Nonetheless, I agree that it's probably not worth it because the elements aren't even focusable by default.

**Comment by facelessuser** [comment]
I've added a simple label of `task` to the items.

**Comment by squidfunk** [comment]
@facelessuser the latest change makes the generated HTML not conform to the spec anymore, as the suggestion by the OP is invalid HTML. Try to check this minimum reproducible example in the [W3C validator](https://validator.w3.org/nu/#textarea):

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test</title>
  </head>
  <body><input type="hidden" label="task" /></body>
</html>
```

The resulting report denotes that `label` is not a valid attribute:

<img width="577" alt="Bildschirmfoto 2020-12-06 um 11 31 23" src="https://user-images.githubusercontent.com/932156/101277719-96e38200-37b6-11eb-9fe6-f5ec020fd48f.png">

According the [W3C spec](https://www.w3.org/TR/html401/interact/forms.html#edef-LABEL), inputs and labels can be associated either explicitly with a combination of `label[for=foo]` and `input[id=foo]`, or implicitly by locating the `input` inside the label. This is exactly what my latest comment is about - moving the text into the `label` next to the `input` is not only valid HTML, but should also improve accessibility.

I'd recommend to revert the latest change, as downstream HTML sanitation pipelines will report this as an error.

**Comment by facelessuser** [comment]
Then I'll most likely remove the attribute and probably do nothing. Moving text into the label isn't going to fly, especially with complex list items. And we honestly don't need IDs for these.

**Comment by facelessuser** [comment]
TBH, I'm not seeing these inputs take focus through tabbing. Maybe that is because they are not in a `form` element? So I'm not seeing this as an actual problem (the missing labels).

Moving content of task list under the "custom" label (because we don't have a label element for non-custom task lists) doesn't seem practical as we may move whole nested lists and such under an input.

Adding additional ids just creates more noise for header elements. I don't want to inject more IDs that conflict with header ids. Especially since these are not editable inputs that anyone ever needs to focus on.

If anything, I'd prefer a solution to prevent task lists from taking focus as we don't focus normal list items either, but currently, I don't see these task lists taking focus, so I'm thinking this lighthouse error is not really relevant to us.

I'm open to further discussion, but I don't think there is anything else for us to do here, but revert the faulty change.

**Comment by facelessuser** [comment]
Revert has been made: https://github.com/facelessuser/pymdown-extensions/commit/20b7ae22b6b21cd36294be6cbc3946216867c317

**Comment by squidfunk** [comment]
Inputs don't get focus because they're disabled. As there's the `clickable_checkbox` checkbox which doesn't mark them as disabled, they're – in theory – clickable. To me, this option makes no sense at all, as it's suggested that the user can interact with the document, but in fact, he can't. Of course, somebody could implement logic which actually persists the state of those elements, but I haven't seen anything like that, and it's probably better to do a custom implementation then.

IMHO this is a hell of a non-problem. I'd rather deprecate the `clickable_checkbox` option that trying to waste too much time in getting Lighthouse to shut up.

**Comment by facelessuser** [comment]
I have no problem with doing nothing more with this. I never make these clickable, and personally see no real use in this, but we'll see if I bother to deprecate it. If people like using them clickable with the noted weakness in accessibility, I'm fine with that.

**Comment by facelessuser** [comment]
On a side note, I don't know why I assumed a label attribute was a thing. It shows how much actual web stuff I do 😅.

**Comment by fabianpiau** [comment]
Thanks guys, for looking into that. And sorry for the hassle! I guess sometimes automated accessibility tools can be a bit picky...
