### ISSUE TITLE
Option to add rel="nofollow" to links for magiclink

### ISSUE THREAD

**Issue by mitchelljkotler** [facelessuser/pymdown-extensions#115]

**Comment by facelessuser** [comment]
You should be able to do this already if you enable the `markdown.extensions.attr` [extension](https://pythonhosted.org/Markdown/extensions/attr_list.html).

I don't see a need to add this specifically when there is something that can do this:

```
[test](http://google.com){: rel="nofollow"}
```

**Comment by mitchelljkotler** [comment]
If I want to allow user generated content with markdown, I want to force
all links to contain rel="nofollow".  I don't see how the attr_list
extension allows for this.

**Comment by facelessuser** [comment]
>  I don't see how the attr_list extension allows for this.

It doesn't do it automatically for all links. But in my defense, the issue contains: `No description provided.`.  Without details,  I can't possibly know what the intended use case for this is. And though I've been training hard at mind reading, I'm not yet able to do it through the internet :slightly_smiling_face:. 

All jokes aside, I'd have to think about this.  I imagine there are a number of user things you'd like to disallow, but I wonder if this would be better suited to a specialized "user generated content" extension.

I'll think about it.  If it does happen, it would be pretty low on my priority list.  This is a very specific use case that I think is very specific to what you are doing.  Most people don't need such a feature, or they just post process the file after rendering and add the attribute.

**Comment by mitchelljkotler** [comment]
Sorry for the poor explanation.

If it's something you think you'd accept, I could submit a pull request -
sseems straight forward to implement.  Otherwise a post processor might be
my best bet.

Thanks

**Comment by facelessuser** [comment]
After thinking about this more, this request just doesn't quite fit with MagicLink's goals.  It is aiming to detect and transform special links or link shorthands, but not really focused on setting mass attributes etc.

I think you'd be better off rolling your own extension that uses a treeporcessor class that walks the HTML tree and adds your attribute. But it may be possible to still miss links that are injected in certain ways, so maybe instead a postprocessor extension class makes more since.

Either way, I just don't think this aligns with MagicLink's current direction.  If the direction changes, I may revisit this in the future, put I think for now I will pass on this feature request.  Thanks for the suggestion and interest though.
