### ISSUE TITLE
feature_request(strip_html): remove extra p tags

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/pymdown-extensions#1197]
### 1. Summary

It would be nice, if StripHTML or any another extension be able to delete extra `p` tags inside `li`.

### 2. Argumentation

1. It’s extra tags, they aren’t needed.
1. [**Interline spacing**](https://en.wikipedia.org/wiki/Leading). See the real list, where items 1, 2 and 3 hasn’t `p` tag, but items 4 and 5 has:

    ![p tag interline spacing](https://i.imgur.com/WSIm7BT.png)

    The interline spacing is different. It isn’t the best idea for design.

1. Extra `p` tags increase a DOM size. A large DOM tree [**isn’t the best idea**](https://web.dev/dom-size/).

### 3. MCVE

1. I have a file `KiraList.md`:

    ```md
    1. Kira first
    <!--- Kira comment -->
    1. Kira second
    ```

2. `python -m markdown KiraList.md`:

    ```html
    <ol>
    <li>Kira first</li>
    </ol>
    <!--- Kira comment -->
    <ol>
    <li>Kira second</li>
    </ol>
    ```

    Not good default behavior; I don’t need the second `ol`.

3. I found the PyPI extension [**python-markdown-comments**](https://pypi.org/project/python-markdown-comments/); `python -m markdown -x mkdcomments KiraList.md`:

    ```html
    <ol>
    <li>
    <p>Kira first</p>
    </li>
    <li>
    <p>Kira second</p>
    </li>
    </ol>
    ```

It’s better, but I can’t found, how I can remove extra `p` tags.

### 4. Not helped

1. [**Tidy**](https://www.html-tidy.org/) don’t delete these tags by default. I can’t find any [**option**](https://api.html-tidy.org/tidy/quickref_next.html) that do it.
1. Also, I can’t found any plugin for Python Markdown, Pelican (my static site generator) or Grunt that can solve this problem.

Thanks.

**Comment by facelessuser** [comment]
## Q &amp; A

There is a lot here and a lot of questions to answer. 

> I found the PyPI extension python-markdown-comments; python -m markdown -x mkdcomments KiraList.md:
>
> It’s better

Better is subjective, but if you prefer it, you are more than happy to use it.

`python-markdown-comments` is done as a preprocessor while StripHtml is a postprocessor.

`python-markdown-comments` could potentially remove comments in code blocks and such. I haven't used it, so I cannot 100% tell you what it can do and cannot do. But I imagine it has broken corner cases as you would need a lot more complexity to work around all cases. This is based on my initial look at the code

StripHtml does wait and execute stripping as a postprocessor so that it can remove the comments once the document is an HTML document so it gets the context right. But, as stated in the documents, this means that comments can affect the parsing of the document, so it would be wise to use comments sparingly and in ways that won't mess up the document.


> I have a file KiraList.md:
> 
> ```
> 1. Kira first
> 
> 1. Kira second
> ```
> 
> python -m markdown KiraList.md:
> 
> ```
> <ol>
> <li>Kira first</li>
> </ol>
> 
> <ol>
> <li>Kira second</li>
> </ol>
> ```
> 
> Not good default behavior; I don’t need the second ol.

As mentioned, StripHtml waits until the postprocessor step to remove comments. That's when the document is an actual HTML and we can remove comments properly within an HTML document so we have the proper context.

Comments are treated as block HTML elements by the parser, so it will break up lists. I don't control the Markdown parser, but that is why it does what it does. I would be careful how you use comments in an HTML document. You are using them with the assumption that they are treated as native Markdown comments, but they are not a comment system native to Markdown, it is HTML, and so it is treated as HTML and actually affects the Markdown parsing.

> how I can remove extra p tags.

Markdown lists have two variants loose lists and tight lists.

```
1. tight
2. lists
```

and

```
1. loose

2. lists
```

Tight lists will not insert a `<p>` except when the content has block contents: multiple paragraphs or list items spaced with empty newlines. This is a feature of Markdown.

So what you are seeing is that even in `python-markdown-comments` the presence of comments affects the parsing. It removes the comments but preserves the line. This triggers a loose list.

## Viability of Stripping Paragraph Tags

So, could I add some complex HTML analysis that could identify that a given `<p>` tag in a list doesn't contain any real block content and could be stripped? Yes. Some people though would purposely want those `<p>` tags as it is a feature though. But then I guess I could add more complexity to determine that when I am removing a comment, does it appear that the `<p>` was introduced by the comment? Well, I guess, but frankly, I think that is a lot of complexity with very little gain.

## Personal Recommendation

I purposely only use comments in such a way as to not influence the Markdown parsing in a significant way. I may comment out a paragraph, Maybe comment before a section. I do not use them between lists, and I would advise you do not as well.

What it sounds like you actually want is a list parser that doesn't do loose lists when there are empty lines between bullets, and that is beyond the scope of what StripHtml does.

**Comment by facelessuser** [comment]
Closing as there doesn't appear to be a bug or actionable item needed.

**Comment by Kristinita** [comment]
**Type: Solution** :star:

If anyone is looking for how to solve the problem described in this issue, I have made a [**patch**](https://github.com/ryneeverett/python-markdown-comments/pull/9) for the [**python-markdown-comments plugin**](https://github.com/ryneeverett/python-markdown-comments).

It works for [**test cases**](https://github.com/ryneeverett/python-markdown-comments/pull/9/files#diff-9501eff746862b271dbc2fb1e585146e20101849fffac804291d19a0608a0000) and for my real project.

Thanks.
