### ISSUE TITLE
[Feat]: Snippets `check_paths` option to warn instead of fail on `serve`, throw with `build --strict`

### ISSUE THREAD

**Issue by polarathene** [facelessuser/pymdown-extensions#1253]
With MkDocs, you can have `mkdocs.yml` throw an error if a document link is broken but this affects `mkdocs serve` as well, without `strict: true` you'll just be issued a warning.

Presently the snippets extension has `check_paths: true` to mimic similar behaviour, but there is no warning issued if it's disabled. Likewise, I'm not sure if I can do the same or utilize the existing `build --strict` option so that only builds will throw an error.

Useful to fail an error on CI with `--strict` (so as to not require maintaining a separate `mkdocs.yml` config), but not crash the `serve` process for contributors testing and editing a document locally.

**Comment by facelessuser** [comment]
1. MkDocs is a completely separate thing. Unfortunately, I can't solve the MkDocs config issue of having one or more configs for separate settings setup. That is outside the scope of these extensions.

2. As far as a warning, we can maybe add something like that potentially.

@gir-bot remove S: triage
@gir-bot add T: feature, P: maybe

**Comment by polarathene** [comment]
>     1. MkDocs is a completely separate thing.

Ah sorry, I'm new to MkDocs and learned about your useful extensions from the MkDocs Material theme docs. Seeing as this project also used MkDocs for it's docs, I was under the impression that these extensions were specific to that :sweat_smile: 

Being able to raise a warning I think is sufficient. IIRC I read somewhere that `--strict` will throw an error when it encounters a the warning log level. If that's not something compatible, just getting a warning in the terminal output is still helpful either way without causing `mkdocs serve` to crash (or the opposite of not being aware of an invalid path).

Thanks for all the effort put into these useful extensions! :grinning:

**Comment by polarathene** [comment]
Does supporting emission of a warning involve adding a line here if the `check_paths` condition is not true?:

https://github.com/facelessuser/pymdown-extensions/blob/63de7ea258b3e4141c24b8f84a3ec276499866b5/pymdownx/snippets.py#L128-L129

I'm not a python developer, so I'm not quite sure what the syntax is for emitting a warning is. Looking at [`mkdocs` on github](https://github.com/mkdocs/mkdocs/blob/dd903d3092a9288f6c1ab2291b0a176a48351611/mkdocs/utils/__init__.py#L327-L329) there seems to be what I presume is [a native/builtin Python `logging` library](https://docs.python.org/3/howto/logging.html#when-to-use-logging). `mkdocs` uses it like this:

```python
import logging

# ...

log = logging.getLogger(__name__)

# ...

log.warning("The theme %s is provided by the Python packages "
            "'%s'. The one in %s will be used.",
            theme.name, ','.join(multiple_packages), theme.dist.key)
```

They additionally catch the warnings for their `--strict` build failure via [this filter class](https://github.com/mkdocs/mkdocs/blob/dd903d3092a9288f6c1ab2291b0a176a48351611/mkdocs/utils/__init__.py#L418-L429):

```python
class WarningFilter(logging.Filter):
    """ Counts all WARNING level log messages. """
    count = 0

    def filter(self, record):
        if record.levelno == logging.WARNING:
            self.count += 1
        return True


# A global instance to use throughout package
warning_filter = WarningFilter()
```

And the `mkdocs build --strict` command logic [uses that filter](https://github.com/mkdocs/mkdocs/blob/dd903d3092a9288f6c1ab2291b0a176a48351611/mkdocs/commands/build.py#L312-L313) like so to fail a build:

```python
log.addFilter(utils.warning_filter)

# ...

if config['strict'] and utils.warning_filter.count:
    raise SystemExit('\nExited with {} warnings in strict mode.'.format(utils.warning_filter.count))
```

You'd probably be able to tell from the above if that means `snippets` emitting a warning would also trigger a failure or not be caught as a result. Does it look compatible?

**Comment by facelessuser** [comment]
It would have to run an experiment. It may work, I'd just have to confrim.

**Comment by facelessuser** [comment]
So I ran a test recently, emitting a warning instead of an error, and while it prints, MkDocs does not see it and does not change behavior due to it:

```console
➜  pymdown-extensions git:(feature/auto-snippet) ✗ python3 -m mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/facelessuser/Code/github/pymdown-extensions/site
/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/snippets.py:170: PymdownxSnippetsWarning: Snippet at path bad.txt could not be found
  return self.parse_snippets(lines)
INFO    -  Documentation built in 7.61 seconds
➜  pymdown-extensions git:(feature/auto-snippet) ✗ python3 -m mkdocs build --strict
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/facelessuser/Code/github/pymdown-extensions/site
/Users/facelessuser/Code/github/pymdown-extensions/pymdownx/snippets.py:170: PymdownxSnippetsWarning: Snippet at path bad.txt could not be found
  return self.parse_snippets(lines)
INFO    -  Documentation built in 7.49 seconds
```

I don't know if there is any other trickery we could do to make MkDocs see it, but as I mentioned earlier, PyMdown Extensions is not specifically linked to MkDocs, and it doesn't make sense to add a bunch of MkDocs specific code to try and trick MkDocs into seeing the warning and treating it as it's own.

In all honesty, it makes sense MkDocs doesn't trigger our warnings. Can you imagine documents failing for any deprecation warning any library it uses emits?

While I could make 'error' vs 'warning' an option, but it won't specifically solve your issue of maintaining two different `mkdocs.yml` files to enable or disable checking based on strict settings.

**Comment by polarathene** [comment]
Thanks for looking into that :)

Being able to output an warning instead of throwing an error might be useful, but for my concern with CI detecting the issue I guess I'll just stick with throwing an error.

**Comment by pawamoy** [comment]
Hello! Coming to this thread with some useful info :slightly_smiling_face: 

Context: I develop mkdocstrings, a MkDocs plugin. mkdocstrings uses different "handlers" to support multiple languages. The Python handler uses another tool called Griffe, which I develop as well.

Just like extensions, Griffe knows nothing about MkDocs. Still, I wanted to integrate its emitted warnings into MkDocs, so that they would fail the build when strict mode is enabled. So here's how I did this, in an elegant way I think:

- Griffe uses loggers that can be *patched*
- the mkdocstrings Python handler patches these loggers with custom ones that are "recognized" by MkDocs

It means that when Griffe runs in standalone mode, it emits warnings on stdout (stderr?), normally. But when it is used through mkdocstrings, warnings are picked up by MkDocs and they make the build fail if strict mode is activated.

Griffe's loggers reference: https://mkdocstrings.github.io/griffe/reference/griffe/logger/
Griffe's loggers code: https://github.com/mkdocstrings/griffe/blob/74420d98addea61073080ad69ac8b7930c0c7bdf/src/griffe/logger.py
How it's used in the Python handler: https://github.com/mkdocstrings/python/blob/7e17fc41fda90d1d91d021ed53d3405f6c057b77/src/mkdocstrings_handlers/python/handler.py#L23-L29

```python
from griffe.logger import patch_loggers
from mkdocstrings.loggers import get_logger

logger = get_logger(__name__)

patch_loggers(get_logger)
```

mkdocstrings's `get_logger`:

https://github.com/mkdocstrings/mkdocstrings/blob/cccebc40c0d51c23381d53432d9355fba9a290ae/src/mkdocstrings/loggers.py#L115-L126

Note that we use `mkdocs.plugins.{name}` as logger name: that's the actual hack that allows MkDocs to pick up the warnings.

> Can you imagine documents failing for any deprecation warning any library it uses emits?

A deprecation warning is not the same as a logging warning. With this, logging warnings are picked up by MkDocs, but deprecation warnings (and every other type of warning emitted with `warnings.warn` such as `UserWarning`, `PendingDeprecationWarning`, etc.) will be processed as usual (in respect to PYTHONWARNINGS).

Also, only your own logs are picked up by MkDocs, since only they are emitted from a logger dressed as a MkDocs logger. Your dependencies logs still pertain to their own loggers, which are not MkDocs loggers, and therefore are not picked up by MkDocs.

Anyway, that's just how I did it, and pymdownx's sitation is not the same here, since there's no intermediary like mkdocstrings handlers to patch loggers, unless someone writes a MkDocs plugin to do just that.
