### ISSUE TITLE
Extra space is added for subscripts and superscripts

### ISSUE THREAD

**Issue by dmitry-radzevich** [facelessuser/pymdown-extensions#1312]
An extra space is added inside and around `<sub/>` and `<sup/>` tags generated by Tilde and Caret extensions. This is theme-independent and has been around since ages (and still happens in the latest published version).

### Original Document

```
# Tilde & Caret

## Subscripts

Simple~subscript~

Complex~subscript\ with\ escaped\ spaces~

H~3~PO~4~
H~2~O

## Superscripts

Cu^2+^

x^2^ + y^2^ = z^2^

ADF~PKCS#15~
```

### Expected Display

![image](https://user-images.githubusercontent.com/58784299/115950949-75253600-a4de-11eb-84b8-ef7d80c737c2.png)

```
<p>
        H<sub>3</sub>PO<sub>4</sub>H<sub>2</sub>O
</p>
```

### Rendered by Plugins

![image](https://user-images.githubusercontent.com/58784299/115950717-380c7400-a4dd-11eb-9fba-bcd1b1152edc.png)

The reason is extra spaces in generated HTML (if I remove them manually, everything starts looking as expected) due to tags beatifying (indentation) + an extra space is added before the content itself. 

I'd expect the paragraph text not to be broken up / reformatted (i.e. span-like behavior is expected) byTilde & Caret.

![image](https://user-images.githubusercontent.com/58784299/115950803-b406bc00-a4dd-11eb-8d60-45788d322ca3.png)

```
<p>
        H
        <sub>
         3
        </sub>
        PO
        <sub>
         4
        </sub>
        H
        <sub>
         2
        </sub>
        O
       </p>
```

**Comment by facelessuser** [comment]
@dmitry-radzevich, I'm not so interested in what your browser is showing me. Browsers have a tendency to normalize content and apply certain styles in certain cases, and there is still your theme component which I have no way of debugging here. What I'm interested in is simply the input and output. So if calling markdown with my plugin was to provide an output with spaces in the raw HTML, then I would think you have a good argument. Unfortunately, that is not what I see:

```py
>>> from markdown import markdown
>>> markdown('Complex~subscript\ with\ escaped\ spaces~', extensions=['pymdownx.tilde'])
'<p>Complex<sub>subscript with escaped spaces</sub></p>'
>>> markdown('H~3~PO~4~', extensions=['pymdownx.tilde'])
'<p>H<sub>3</sub>PO<sub>4</sub></p>'
```

From what I see above, I see absolutely no issue. If you do not like what a browser or theme does with your subscripts or superscripts, you will have to do some additional styling to get the desired output.

As you can see in my browser output, from the official documentation that uses `tilde` to render subscripts and superscripts, you will also see no additional spaces:

<img width="356" alt="Screen Shot 2021-04-24 at 7 59 12 AM" src="https://user-images.githubusercontent.com/1055125/115961428-76049a80-a4d3-11eb-84b9-e6f2161d9fc7.png">

I do not "intelligently" add white space or format subscripts and superscripts to look different under any conditions. We simply output what is provided.

If you can show me otherwise, I'd be happy to take a look, but from my tests, I'm thinking this is a user error and not a plugin issue.

@gir-bot remove S: triage
@gir-bot add S: wontfix

**Comment by dmitry-radzevich** [comment]
hi @facelessuser , I got your point. The problem is that I've tried to create a minimal setup and an isolated test case for that (mkdocs + pymdownx) and the problem is visible in the HTML generated (as I posted above). 

Seems like it's pymdownx integration with mkdocs that doesn't play nice here. Thanks anyway, will try to debug that more.

**Comment by facelessuser** [comment]
I use Mkdocs with mkdocs-material. I don't see issues there. If there is an isolated way to test, it is what I showed in my previous post. The output is clearly not created with extra space. Any spaces are being added by some other process before or after pymdownx parses and returns the tags, but not during the parsing.

I would look at other extensions and such (either Python Markdown extensions or MkDocs plugins) as they may be altering Markdown content before we parse it or altering HTML after we process it, it is certainly not during our processing of it.

**Comment by facelessuser** [comment]
Ah, I see you could the culprit :). I missed that in my last post, or the previous post was edited after I posted. Either way, I think it is safe to say they're is nothing for pymdownx to do.
