### ISSUE TITLE
[feature request] snippets include files from url

### ISSUE THREAD

**Issue by fjp** [facelessuser/pymdown-extensions#1350]
Hi, with the snippets extension, is it possible to include (parts from) external files? For example to include source files using their url from another repository, something like:

```
--8<-- "https://raw.githubusercontent.com/github-organization/repository-name/main/path/to/file.txt"
```

**Comment by fjp** [comment]
A plugin that seems to provide this feature is: https://github.com/mprivat/mkdocs-snippet-plugin (I haven't tried it yet).

**Comment by facelessuser** [comment]
Snippets does not currently download external files. I guess it could. It's not something I've had a need for, but I guess we could add something. I've been asked a number of times about this, so maybe it is worth adding.

@gir-bot remove S: triage
@gir-bot add T: feature, P: maybe

**Comment by facelessuser** [comment]
Sure, and if that file ever changes, you'll snip the wrong piece. If you manage all the pieces that's fine I guess, though I suspect people will forget to update all references when doing so. This is a subjective argument though, I don't have to find it practical for others to view it useful, but this is why I don't place high value/priority on such a feature.

As far as URL snippets in general, I still think I'm okay with it, even if I have no intentions of using them in real-world documents.

**Comment by jstafford5380** [comment]
> Sure, and if that file ever changes, you'll snip the wrong piece.

True. Well like I said, it's a feature in DocFx so someone somewhere justified it at some point. Likely use case is almost certainly internal documentation, but yeah it would be on the maintainers to deal with that.

**Comment by facelessuser** [comment]
I'm looking into adding URL support. There are some limits I plan on imposing:

1. By default, we will have an arbitrary size limit, this can be configured.
2. We will have a default timeout, again, this can be configured.
3. If we are downloading a URL, snippets within it will not be processed as local file paths. A URL snippet can only contain other URL snippets.

Like files, a missing link will fail silently unless `check_paths` is enabled, and all other failures will bubble up: timeouts, etc.

This is a work in progress, but I imagine sometime soon I'll have something up. This does not handle any line numbers, just imports from external URLs instead of local files.

**Comment by facelessuser** [comment]
Went ahead and just posted the experimental branch. I'll be working on getting it in the next release.
