### ISSUE TITLE
pymdownx.superfences breaks the mermaid2 plugin for mkdocs

### ISSUE THREAD

**Issue by maxmar391** [facelessuser/pymdown-extensions#1440]
Dear all,
I think your extensions are great work! I love working with them.

I have now encountered an issue which I wanted to report. When using the pymdownx.superfences extensions and the mermaid2 plugin together with mkdocs (i.e. activating the pymdownx.superfences extension in the "markdown_extensions" section and the mermaid2 plugin in the "plugins" section of the mkdocs.yml config file), the mermaid diagrams are not rendered anymore. The mkdocs website shows only the source code of the mermaid diagram.

I am not sure, if this is a problem on the side of the pymdownx.superfences extension or of the mermaid2 plugin.

Has anyone seen this behavior before?

All the best,
Max

**Comment by facelessuser** [comment]
@maxmar391, sorry to hear that you are having issues with `mermaid2` plugin. I have attempted to work with the author to get their plugin working: https://github.com/facelessuser/pymdown-extensions/issues/964.  I have given them all the advice that I can. I'm not sure if you are using it wrong, or they are doing something incorrectly, but there is nothing wrong with SuperFences. I believe, because of the way they wrap the results in DIVs that the `mkdocs-minify-plugin` messes with the content and breaks it. This is not a SuperFences issue, but an issue of compatibility of how they choose to wrap their content. I personally do not wrap my content like they do and can use `mkdocs-minify-plugin` just fine.

I do not directly support `mermaid2` and if there are issues, you should file an issue on their repository. They are using SuperFences to crate mermaid diagrams, not the other way around.

I have provided advanced notes to get Mermaid working and to get around the inherent issues involved: https://facelessuser.github.io/pymdown-extensions/extras/mermaid/. Those documents even include a loader that should help in doing this yourself. 

Themes like https://github.com/squidfunk/mkdocs-material have taken those notes and implemented something very similar that works. Currently, it is only available for those in their "insiders" program, but when it goes public, it will be available generally to those using the Material theme.

@gir-bot remove S: triage
@gir-bot add S: wontfix
