### ISSUE TITLE
Add the ability to display shell / terminal commands input and output

### ISSUE THREAD

**Issue by ben519** [facelessuser/pymdown-extensions#1802]
### Description

[Superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) is great for display code blocks, but sometimes I want to display inputs and outputs as they appear in a shell prompt.

**Example**

Here's what a typical `git status` looks like in my zsh shell.

<img width="554" alt="Screen Shot 2022-09-10 at 8 42 44 PM" src="https://user-images.githubusercontent.com/723099/189508100-e0543f0f-88e5-4c0e-aff7-585c7afa9938.png">

Mimicking this prompt with the superfences is difficult. I would typically leave out the *prompt* (`bgorman@Bens-MacBook-Pro-2 %`) and just write

```
git status

# On branch booger
# 
# No commits yet
```

Note that I also comment the output to differentiate it from the input.

**Request**  
My request is to provide some functionality that lets me write input/output as it appears in a typical shell command. Something like this

```
bgorman@Bens-MacBook-Pro-2 % git status

On branch booger

No commits yet
```

However, the "Copy to clipboard" button should exclude `bgorman@Bens-MacBook-Pro-2 %`.

### Benefits

Shell commands are a common part of documentation for many software packages. Making it easier to display and distinguish input and output within a shell will help readers interpret commands.

## Solution 1

Similar to how [critic](https://facelessuser.github.io/pymdown-extensions/extensions/critic/) works, provide some syntax that can wrap text in a code block which excludes it from being copied when a user clicks the "Copy to clipboard" button.

**Example**

```
{---user1>--} git status

On branch main

No commits yet
```

The above code block would be rendered like this

```
user1> git status

On branch main

No commits yet
```

But then the user copies the block, only the following text will be copied:

```
git status

On branch main

No commits yet
```

## Solution 2

Create a `prompt` argument which can be set like this

```
```prompt="root@localhost#"
root@localhost# git status

On branch main

No commits yet
```.
```

With this technique, prompts can be identified and excluded from the copy command. Furthermore, prompts could boldened to differentiate them from commands.

**Comment by facelessuser** [comment]
I'm really not understanding exactly what the request is. What language do you use with such code blocks?

I use `console`, and Pygments will assign the `gp` class to the prompts. Depending on your color scheme for Pygments, this may show a different color, format, or none at all.

 If you'd like to style them and/or ignore them, you can turn on `pygments_lang_class` in `pymdownx.highlight` which will attach the class `language-console` to the outer wrapper, and then you ignore/style `.language-console .gp` if you desire. I'm not sure there needs to be any kind of special handling.

```css
.language-console .gp {
    font-weight: 800;
    user-select: none;
}
```

As you can see, I cannot physically copy the prompt anymore:

![prompt](https://user-images.githubusercontent.com/1055125/189510449-a665d722-fe66-4e6e-aa5a-14718235e5f0.gif)

Now, what I can't control is the mechanism by which an implemented copy button may extract text, so that would be up to whatever implementation that automates copying code from a code block to respect such rules or filter out such classes.

**Comment by ben519** [comment]
This is exactly the behavior I was looking for, thanks! (The lexer I use for shell commands is typically `commandline`).
