### ISSUE TITLE
Snippets don't support jinja2 templating from mkdocs_macros_plugin

### ISSUE THREAD

**Issue by orbsmiv** [facelessuser/pymdown-extensions#1948]
### Description

Variables and jinja2 code that are provided through the MkDocs Macros plugin are not rendered in pymdown snippets.
(https://mkdocs-macros-plugin.readthedocs.io)

### Minimal Reproduction

1. Define some variables either in the yaml frontmatter for a page (see below) or in the `mkdocs.yml` file as described here: https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#configuration-variables
    ```
    ---
    my_var: banana
    ---
    ```
3. Call these variables as templates in a markdown snippet, e.g. `{{ my_var }}`
4. Call the pymdown snippet with `--8<--`
5. Problem: the variable is not rendered but appears in its raw form. The same issue applies with any jinja2 code.

### Version(s) & System Info

- Operating System: macOS 13.1
- Python Version: 3.10.8
- Package Version: 9.9.2

**Comment by orbsmiv** [comment]
To provide some context, we use a large number of variables in the `extra:` bit of the configuration in order to centralise the various external URL links across our docs pages.

**Comment by facelessuser** [comment]
1. Snippets is not a MkDocs or any documentation framework plugin, it is a Python Markdown extension, and as such, is unaware of anything done at the documentation framework level. It is agnostic to all documentation frameworks as it has no knowledge or context associated with any of them.
2. Snippets is a preprocessor and is applied during Markdown to HTML translation. It has a very specific syntax that it recognizes and respects. If it is desired to inject Jinja variables, then an appropriate preprocessor for Jinja variables would need to be executed before Snippets and be applied to the file before Snippet processes its own syntax. That would be the responsibility of any MkDocs plugin hoping to piggyback off the Snippet's functionality. To be honest, if you are wanting to use Jinja, you should probably use a Jinja2-specific plugin and do file inclusion through Jinja2.

We do not have the time to look into the inner workings of the macros plugin for MkDocs. If a simple solution was identified that allowed us to work with the plugin, I would be open to hearing the suggestion as long as the solution is not greatly intrusive. We have no desire to couple our logic with another plugin outside of the Python Markdown domain.

As this is purposely an extension meant for simple file inclusion and is not meant to be an advanced templating solution, the issue is not a bug, but expected, and beyond the scope of the extension. Thanks for filing the issue, but we will have to pass on this issue. I am open to simple, non-intrusive proposals if a simple compromise was discovered, but this will not be something that we will specifically be investigating.

@gir-bot remove S: triage
@gir-bot add S: rejected

**Comment by ernestre** [comment]
@orbsmiv have you found a workaround for this? I have the same situation :sweat_smile:

**Comment by orbsmiv** [comment]
> @orbsmiv have you found a workaround for this? I have the same situation 😅

@ernestre unfortunately no, although I've not looked into it much recently. I instead settled on using the _include_ directive in MkDocs Macros:  
<https://mkdocs-macros-plugin.readthedocs.io/en/stable/advanced/#including-external-files-in-pages>

The problem with this is that it doesn't respect indentation, whereas pymdown snippets do, so any included documents will need to match the indentation required at the parent level, making them a bit less flexible.

**Comment by ernestre** [comment]
> > @orbsmiv have you found a workaround for this? I have the same situation 😅
> 
> @ernestre unfortunately no, although I've not looked into it much recently. I instead settled on using the _include_ directive in MkDocs Macros: https://mkdocs-macros-plugin.readthedocs.io/en/stable/advanced/#including-external-files-in-pages
> 
> The problem with this is that it doesn't respect indentation, whereas pymdown snippets do, so any included documents will need to match the indentation required at the parent level, making them a bit less flexible.

I've switched to using includes also and I think i've found a solution for the indentation using jinja2 filters. However you need to define the indentation level yourself:

```jinja
{% filter indent(width=4) %}
{% include "resources/image.md" %}
{% include "resources/volumes.md" %}
{% endfilter %}
```
