### ISSUE TITLE
URL snippet caching doesn't work as expected

### ISSUE THREAD

**Issue by iamjackg** [facelessuser/pymdown-extensions#1972]
### Description

I've been using the URL snippet functionality for a while, and noticed that it was slowing down the rendering process quite a bit. I took a look at the code, and it looks like `download()` was intended to be memoized using the `lru_function` decorator, but it seems to me like that can't work, since an entirely new `SnippetPreprocessor` is created for each page.

### Minimal Reproduction

I tested this with a simple `print("download", self, url)` in `download()`, and the `SnipperPreprocessor` is indeed different every time, which means the URL is downloaded once per page. Is this intended?

```
download <pymdownx.snippets.SnippetPreprocessor object at 0x7fe7447d2670> https://[...]
download <pymdownx.snippets.SnippetPreprocessor object at 0x7fe74478c310> https://[...]
download <pymdownx.snippets.SnippetPreprocessor object at 0x7fe7447729d0> https://[...]
download <pymdownx.snippets.SnippetPreprocessor object at 0x7fe74465e700> https://[...]
download <pymdownx.snippets.SnippetPreprocessor object at 0x7fe74465ec40> https://[...]
download <pymdownx.snippets.SnippetPreprocessor object at 0x7fe7445f58e0> https://[...]
[...]
```

### Version(s) & System Info

- Operating System: Linux
- Python Version: 3.11
- Package Version: 9.9

**Comment by facelessuser** [comment]
@iamjackg Unfortunately, your intuition is right. Ideally, MkDocs would reuse the same object and call `.reset()` on it.

So, to cover this issue, I could _maybe_ fix it my not using class method. That now means I have to make sure the request headers are hashable, so I'd need to create an immutable dictionary that can be hashed and convert the specified headers to this new type. Hopefully, requests won't care and will process without issue.

Now we have an issue were once you import the lib and start using it, it caches the request forever (or until the cache overflows). So now we need a way to invalidate the cache. If we invalidate it on reset, you are back in the same state as before. So, then maybe we globally have to track a timeout for invalidation? That'll affect other processes if it is used by multiple...

I'm not sure the best approach at this time. Ideally, we'd reuse the same object and call `.reset()` on the Markdown instance.

**Comment by iamjackg** [comment]
Heh, yeah, it's a weird situation. Another option could be to have a `cache_downloads` configuration option that will make Snippets use a memoized version of the function (perhaps by calling a static wrapper to the "real" download function), with the caveat that nothing will expire until the cache runs out? MkDocs users could set that to `true` and reap the benefits, while everybody else is none the wiser.

In the meantime, I ended up using https://mkdocs-macros-plugin.readthedocs.io/ to write my own memoized function that downloads and appends the snippet I care about. Custom modules for that plugin are loaded once per build, so the context isn't reloaded for every page.

**Comment by facelessuser** [comment]
Again, Mkdocs should really not have a new instance each time. We could create a global cache method approach (as you suggested) but it seems you've found an alternative solution, so I guess, unless something like this was requested by others, there's probably nothing to do at this time.

**Comment by freya022** [comment]
I'm also having the same issue, using mkdocs, I just started rewriting a wiki, and I already have ~6 seconds wait times between hot reloads, with just [2 pages](https://gh-pages-preview.github.io/Deploy-Previews/freya022/BotCommands-Wiki/6/using-commands/using-slash-commands/writing-slash-commands/), I can only imagine this getting way worse in the future.

I think a good enough solution would be to allow the user to enable a global cache, in which case this should tell the user to restart mkdocs if the cache has to be invalidated.

**Comment by facelessuser** [comment]
In general, I would probably discourage using excessive URL snippets. At least my personal opinion. With that said an optional global cache is very MkDocs specific. In general, any application of Python Markdown should be calling reset and reusing the same Markdown object, but, for whatever reason, MkDocs seems to really not want to do that.

While I won't rule it out as a possibility, it's not a general-purpose feature, but one that specifically caters to MkDocs odd use of Python Markdown which I wouldn't normally be okay with.

**Comment by freya022** [comment]
What would you suggest using instead of URL snippets? I have to use them as my wiki is a separate repository from the project it documents, and the reason I'm using snippets is so I don't have to track each snippet to see if it's still valid after an update, after a breaking change for example

The only solution i see is transferring my wiki to the main project, but that would be quite annoying imo

**Comment by facelessuser** [comment]
I'm not here to tell you what to do, only that sourcing your entire documentation via URLs sounds like a very inefficient approach. Such an approach is an edge case, not the norm. I imagine people are truly using URLs, but not to source a majority of their content, but there are always exceptions to the rules.

Personally, if it were me, I'd probably check the wiki out locally and then source the documents locally. With that said, I'm not privy to exactly where, why, and how you are acquiring this info as little to know information on that is been given to me.

What I can say is I don't like the idea of adding a special global cache to satisfy one application which I feel is using Python Markdown incorrectly. I won't say that I absolutely won't add a global cache, but I would need more time to think about it as I don't like the idea of adding a workaround for things that I feel should be fixed in MkDocs itself.
