### ISSUE TITLE
Allow setting a default language for code blocks

### ISSUE THREAD

**Issue by Aran-Fey** [facelessuser/pymdown-extensions#2001]
### Description

Currently, syntax highlighting is only applied to a code block if I explicitly define the language (like ` ```python`) or I enable the `guess_lang` setting. This sucks because I don't want to repeat the language a million times, and `guess_lang` often guesses wrong.

### Benefits

How would what benefit users? You've only asked me to describe the problem so far. I'll propose a solution below, which will benefit users by eliminating this problem.

### Solution Idea

Add a `default_language` setting.

**Comment by facelessuser** [comment]
This would be a very non-standard behavior. I'm not sure of any markdown setup that does something like this.

**Comment by Aran-Fey** [comment]
In case you're not aware, this extension is [the recommended way](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/) to add syntax highlighting to MkDocs' Material theme. This results in the ridiculous situation that I'm writing documentation for my python project, and yet I have to remind the software that "hey, this is python code, alright?" on *every single* code block I write. It's absolutely ludicrous.

**Comment by facelessuser** [comment]
> In case you're not aware

I am

> This results in the ridiculous situation that I'm writing documentation for my python project, and yet I have to remind the software that "hey, this is python code, alright?

This is the exact way pretty much all Markdown parsers work.

> It's absolutely ludicrous.

Not really, but that is just a difference of opinion.

---

With all of that said, I'll consider it as a possibility, but no promises.

**Comment by facelessuser** [comment]
I've decided to allow default languages to be specified moving forward. This is controlled by the new `default_lang` option in `pymdownx.highlight`. This will _only_ control block code blocks.

This will not be applied to inline blocks by default as it often makes less sense to make such assumptions. Traditionally InlineHilite only applies code styling to blocks with explicit languages, others are just escaped and displayed normally except when using `style_plain_text` which will run all inline blocks through the highlighter and just treat undecorated inline blocks as plain text. Moving forward, if `style_plain_text` specifies a specific language instead of a boolean `True`, undecorated, inline code blocks will be treated with the specified language.
