### ISSUE TITLE
Support extracting images when using snippets

### ISSUE THREAD

**Issue by milkotodorov** [facelessuser/pymdown-extensions#2090]
### Description

When using snippets to embed external .md files it would be beneficial to embed their images too.

### Benefits

Simplify the embedding process

### Solution Idea

The images may be extracted upon compile.

**Comment by facelessuser** [comment]
What do you mean by embedding their images as well? You've provided no examples. If you are including Markdown from one file to another, it should include images, assuming they can be found. I imagine if images aren't relative to the new location, that could cause issues, but we do not rewrite anyl reference locations. As a matter of fact, Snippets pays no attention to the format of what is being included, so it doesn't look for paths to rewrite as the source could be anything, Markdown or not.

**Comment by milkotodorov** [comment]
What I mean is when a files is included from URL. I understand that it is not supported, but just thought it could be useful.

**Comment by milkotodorov** [comment]
I understand - it won't be that simple indeed. It was just a suggestion.

**Comment by facelessuser** [comment]
I do think it is a good suggestion, unfortunately, I think it is out of scope for what I intended Snippets for. Snippets was always meant to be a "dumb" file inserter.  While we have added some intelligence to pull from URLs or specify insertion from lines or marked sections, I think being content-aware and processing it to identify relative, remote images, downloading, and embedding them is a bit more intelligence than I am comfortable with adding at this point.

> It was just a suggestion.

Hopefully, I didn't come off as too critical. I like to ask questions in order to understand exactly what is being asked, and I like to share with requesters why some ideas may not be a good fit.  I don't like to just dismiss ideas, but discuss them and outline why it may or may not be a good fit. With that said, I can sometimes be a little too direct which can affect my tone.

While I think I will be passing on this feature, I do think it is a good idea, it is unfortunately not something I am interested in pursuing at this time.
