### ISSUE TITLE
Snippets Notation does not work when inserting into a table using the `--8<--` syntax

### ISSUE THREAD

**Issue by chrimaho** [facelessuser/pymdown-extensions#2156]
### Description

When I try to add snippets to my markdown files using the `--8<--` syntax into a table, it will not render the text from the files. Only the text `--8<-- "..."`.

### Minimal Reproduction

Let's say that I have the following file structure:

```txt
my-repo
├── docs
│   ├── intro.md
│   └── modules.md
├── src
│   ├── my_package
│   │   ├── __init__.py
│   │   └── first_module.py
│   │   └── second_module.py
│   └── tests
│       └── test_first_module.py
│       └── test_second_module.py
└── mkdocs.yml
```

And my `first_module.py` file looks like this:

```py
"""
Some description of my module.
It does some cool stuff.
"""

def func(var1: str = "foo") -> str:
    return var1
```

The `second_module.py` is set up basically the same.

Now, let's say that my `modules.md` file will look like this:

```md
# Modules

## Overview

There's only two modules in this package:

1. `my_package.first_module`
1. `my_package.second_module`
```

Super simple, right? This works.

Well, if I wanted to add the description from `first_module.py` to `modules.md` using the `--8<--` syntax, I'd do this:

```md
# Modules

## Overview

There's only two modules in this package:

1. `my_package.first_module`

--8<-- "src/my_package/first_module.py:2:3"
```

Again, this will render successfully.

However, what if I wanted to add this snippet in to a _table_ on `modules.md`? The thought process here is that when I have multiple modules, I can add them as a table, each line is a different module, the first column is the name of the module, and the second column is the snippet from the description of the module.

I'd like to use this syntax:

```md
# Modules

## Overview

There's only one module in this package:

  | Module | Description
---|---|---
1. | `my_package.first_module` | --8<-- "src/my_package/first_module.py:2:3"
1. | `my_package.second_module` | --8<-- "src/my_package/second_module.py:2:3"
```

However, when I do this, it will _not_ render the snippett in to the cell on the table. Only the text: `--8<-- "src/my_package/first_module.py:2:3"`.

### Version(s) & System Info

- Operating System: Linux `5.15.90.1-microsoft-standard-WSL2`
- Python Version: `3.10.6`
- Package Version: `10.1`

**Comment by facelessuser** [comment]
Snippets requires the syntax to be on a line by itself. It does not currently support inline insertions. So this is not a bug.

This is noted in the documentation:

> The important thing is that the notation must reside on a line(s) by itself, and the path, must be quoted in the case of the single line notation. If the file name is indented, the content will be indented to that level as well.

In summary, this is okay:

```
--8<-- "somefile"
```

This is not:

```
Some text --8<-- "somefile"
```

This is just a limitation of Snippets at this point in time. There are currently no plans to support inline. I don't know if this will change or not in the future.

**Comment by chrimaho** [comment]
I understand. Thank you for clarifying 👍

**Comment by AmoreCadenza** [comment]
@facelessuser: Any chance of reconsidering support for inline snippets as a new feature?

I ran into the same situation as the OP and having an inline embed syntax for snippets would be a game changer for managing Markdown tables with long cells.

**Comment by facelessuser** [comment]
@AmoreCadenza I think you may have a certain vision of how you think it might work, but I don't think it would work the way you want. Granted, I'm speculating, but let me elaborate.

I assume most people think that if I added inline snippets, you could link to complex markup and have it inserted into a table cell, but since Snippets is a simple preprocessor, it would just insert the complex content and send it through the Markdown parser. This means if the complex markup wouldn't work in the cell before snippets, it wouldn't work in the cell if Snippets added such support. This right here means Snippets is likely not well suited for this and would have to be reworked to do something far greater than it currently does.

Let's assume I went through the trouble of trying to process the content and injected a placeholder for the Markdown content that later gets replaced with the content with fully processed content. It would have to be done in a sandbox divorced from the content in the parent. That means relationships with generated IDs and links would be missing.

Maybe I could try and do it on the fly and handle them only when the snippets are handled during inline processing, I would then have the run the entire processing pipeline on the content because the preprocessor didn't see the content as it didn't exist until it was encountered. Will running this out of place cause problems? I am not confident all the issues encountered could be solved, and I'm not too keen on trying to untangle that knot.

It is possible I don't understand the use case you desire, and maybe your use case is far simpler than what I'm thinking, but I imagine there are generally bigger expectations from the wider audience, and I don't think they would get what they think they'd get.

**Comment by AmoreCadenza** [comment]
@facelessuser: Thanks for the quick and thoughtful response. You raise a great point with the potential impression this feature could create as being a way to sneak complex markup into a table cell, and how bad a user experience that would be without fundamentally altering what Snippets is (and altering it into a much more complex tool at that).

My use case is fortunately a simple one - I'm after a way to move the contents of abnormally long table cells out of the table, which the "automated copy-paste" nature of a snippet struck me as perfect for. Here's an example of such a table:

`departments.md`:
```markdown
| Department | How to contact                                                                                                                                                                                                                             |
|------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Leadership | Send an email to [leadership@](mailto:leadership@eq.example)                                                                                                                                                                               |
| Legal      | Send an email to [legal@ cc'ing leadership@](mailto:legal@eq.example?cc=leadership@eq.example), send a message to the [#ask-legal] chatroom, and [call +879-55-55555-555](tel:+879-55-55555-555) if you don't hear back within 30 minutes. | 
| Research   | Send a message to the [#ask-research] chatroom                                                                                                                                                                                             |
| Treasury   | [Open a ticket in the Treasury Help Desk][Create a new Treasury ticket]                                                                                                                                                                    |

[#ask-legal]: https://chat.example/url/to/room
[#ask-research]: https://chat.example/url/to/room
[Create a new Treasury ticket]: https://helpdesk.example/tickets/new?ticket[department]=treasury
```

I have three ideas in mind for how this could work:

## Option 1: Closest to current functionality

The "obvious" approach:

`departments.md`:
```markdown
| Department | How to contact                                                            |
|------------|---------------------------------------------------------------------------|
| Leadership | Send an email to [leadership@](mailto:leadership@eq.example)              |
| Legal      | --8<-- "contact-snippets.md:how-to-contact-legal"                         | 
| Research   | Send a message to the [#ask-research] chatroom                            |
| Treasury   | [Open a ticket][Create a new Treasury ticket] in the [Treasury Help Desk] |

[#ask-legal]: https://chat.example/url/to/room
[#ask-research]: https://chat.example/url/to/room
[Create a new Treasury ticket]: https://helpdesk.example/tickets/new?ticket[department]=treasury
```

`contact-snippets.md`:
```markdown
--8<-- [start:how-to-contact-legal]
Send an email to [legal@ cc'ing leadership@](mailto:legal@eq.example?cc=leadership@eq.example), send a message to the [#ask-legal] chatroom, and [call +879-55-55555-555](tel:+879-55-55555-555) if you don't hear back within 30 minutes.
--8<-- [end:how-to-contact-legal]
```

It would have the caveat you raised of possibly setting user expectations too high but would work and also be very flexible for non-table use cases.

## Option 2: New syntax for same-file snippets

For this use case, a "same-file" syntax - to allow defining a snippet in the same file it's used in (similar in spirit to [footnotes] or [reference-style links]) - would be more convenient:

`departments.md`:
```markdown
| Department | How to contact                                                            |
|------------|---------------------------------------------------------------------------|
| Leadership | Send an email to [leadership@](mailto:leadership@eq.example)              |
| Legal      | --8<--[How to contact Legal]--                                            | 
| Research   | Send a message to the [#ask-research] chatroom                            |
| Treasury   | [Open a ticket][Create a new Treasury ticket] in the [Treasury Help Desk] |

--8<-- [start:How to contact Legal]
Send an email to [legal@ cc'ing leadership@](mailto:legal@eq.example?cc=leadership@eq.example), send a message to the [#ask-legal] chatroom, and [call +879-55-55555-555](tel:+879-55-55555-555) if you don't hear back within 30 minutes.
--8<-- [end:How to contact Legal]

[#ask-legal]: https://chat.example/url/to/room
[#ask-research]: https://chat.example/url/to/room
[Create a new Treasury ticket]: https://helpdesk.example/tickets/new?ticket[department]=treasury
```

Tucking the "extra-long cell" right under the table like that would be awesome. It has the same caveat as Option 1 but limiting inline snippets to living in the same file may encourage users to keep them simpler. The main benefits here are a simpler filename-less syntax for the snippet and being able to edit the snippet in the same file where it's used (likely very close to where it's used, as in my example).

[footnotes]: <https://www.markdownguide.org/extended-syntax/#footnotes>
[reference-style links]: <https://www.markdownguide.org/basic-syntax/#reference-style-links>

## Option 3: New single-line syntax for same-file snippets

Similar to Option 2 but limits inline-compatible snippet definitions to a single line - very much like [reference-style links]. This would minimize boilerplate and - if it's the only way of inserting an inline snippet - will make it impossible to even _try_ inserting multiline snippets into tables (I imagine this is the most common incompatible "complex markup" that users will try to insert into tables with other approaches, per your concern).

`departments.md`:

```markdown
| Department | How to contact                                                            |
|------------|---------------------------------------------------------------------------|
| Leadership | Send an email to [leadership@](mailto:leadership@eq.example)              |
| Legal      | --8<--[How to contact Legal]--                                            | 
| Research   | Send a message to the [#ask-research] chatroom                            |
| Treasury   | [Open a ticket][Create a new Treasury ticket] in the [Treasury Help Desk] |

--8<--[How to contact Legal]: Send an email to [legal@ cc'ing leadership@](mailto:legal@eq.example?cc=leadership@eq.example), send a message to the [#ask-legal] chatroom, and [call +879-55-55555-555](tel:+879-55-55555-555) if you don't hear back within 30 minutes.

[#ask-legal]: https://chat.example/url/to/room
[#ask-research]: https://chat.example/url/to/room
[Create a new Treasury ticket]: https://helpdesk.example/tickets/new?ticket[department]=treasury
```

This mitigates the user expectations problem while still allowing Snippets to remain a "simple" preprocessor.

***

Might any of these approaches fit with your vision for this library or inspire one that could? I'm especially hopeful about #⁠3.

Options 2 & 3 could also be achieved in ways that allow (or even require - easier to implement?) sourcing inline snippets from "snippet files". I considered opening a separate feature request to support same-file snippet definitions but then realized that a simpler filename-less syntax could double as a simplified syntax for inline snippets, which is why I combined the ideas here.

**Comment by facelessuser** [comment]
@AmoreCadenza I think the idea could generally be useful, especially for complex insertions. I'm not sure that Snippets is quite the tool for it as the functionality you are requesting is a bit different and out of scope for it.

But I think maybe an additional plugin could be used. I might even consider implementing such a plugin as I've run into issues where something like what you mention could be useful.

I think we could use the new [general purpose block syntax](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/) to create blocks were we could render content outside of troublesome areas and use some undecided inline syntax to create placeholders. later, during the treeprocessor phase, we could most likely replace the placeholders with the rendered content. 

````
| Column1 | Column2                         |
|---------|---------------------------------|
| A       | Some _simple_ content           |
| B       | Some more _simple_ content      | 
| C       | <complex-content>               |
| D       | <more-complex-content>          |

/// insert | complex-content
- Some content that would never work in a table cell.
- Because the content is a block.
- But you could use it for anything.
- `<complex-content>` is not an actual syntax, but some inline approach could be used.
///

/// insert | more-complex-content
```py
import stuff

# More content that would never work in a table.
stuff.do_stuf()
```
///
````

Anyway, a separate plugin aimed at this kind of work may make sense.

**Comment by facelessuser** [comment]
I think continuing this conversation would require a separate issue or discussion opened.
