### ISSUE TITLE
Accept markdown headers as snippet sections

### ISSUE THREAD

**Issue by DaniBodor** [facelessuser/pymdown-extensions#2536]
### Description

I use snippets to include certain information from my README.md in my other documentation files. This way, I don't need to write those sections out more than once.

It would be great if the [snippets sections](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/?h=snippets#snippet-sections) could recognize existing headers in markdown files and use those as sections, without having to add the snippet specific identifiers into a markdown file.

### Benefits

Given that markdown files are often naturally broken into sections anyway using # to indicate headers, it would intuitively make sense to use these sections as the snippet sections. Before diving into your documentation, I had naturally assumed that this is how it would work (as did the generative tools that I use for such tasks). Given that it seems to be a common assumption that this would work, it would save users the effort of diving into the documentation to figure out the actual syntax required.

**Comment by facelessuser** [comment]
> It would be great if the [snippets sections](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/?h=snippets#snippet-sections) could recognize existing headers in markdown files and use those as sections, without having to add the snippet specific identifiers into a markdown file.

It would be, but there are reasons we don't.

1. We are in a preprocessor state, so we would need to be able to process the Markdown itself. That means identifying headers in code blocks that we want to ignore, potentially someone numbering something like `#1`. Headers logic embedded in HTML that it isn't suppose to process, etc.
2. Snippets was designed with a unique syntax that can be identified and, as documented, does not care about context of the file: code blocks, HTML, etc.

> Given that it seems to be a common assumption that this would work

I disagree with this statement. There may be people who see the name and may hope for such a feature, but I don't know why this would be a common assumption.

1. I specifically document the behavior so that there is no assumption needed. I cannot help what people assume.
2. Considering it uses a unique syntax, I don't know why people would make such an assumption.  It's meant to include files, and only in this [section](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-sections) do we let the user know they can include something other than a whole file or specific lines from the file, and in here we document what it is we actually require to do so.

I understand the desire for such a feature, and I can even admit that it would be interesting feature, but it may simply be beyond the scope of what I am committed to supporting.

**Comment by facelessuser** [comment]
I have no plans to currently offer the requested functionality. I cannot promise what future me may decide, but currently, I have no plans.

**Comment by facelessuser** [comment]
Closing per the aforementioned reasons.
