### ISSUE TITLE
A problem of SuperFences Line Number extension.

### ISSUE THREAD

**Issue by LennonChin** [facelessuser/pymdown-extensions#309]
Hello,

Prefect Extensions, Thank you.

But I find some problem when I use SuperFences extension.

Line number extension rendered result implemented by `table` Tag, but this way has a problem, if I want to word-break a line when it is to long, then the line numbers will not enough to satisfy code lines, you can see this problem at this page [https://blog.coderap.com/article/15](https://blog.coderap.com/article/15), at the bottom of first code block.

Another way to implement line number is use `ul` and `li` tags, it seems that this way cannot provide line start and line step.

**Comment by facelessuser** [comment]
This is not directly a SuperFences issue.  SuperFences currently sends code through the `pymdownx.highlight` extension to highlight code.  It will use [`Codehilite`](https://python-markdown.github.io/extensions/code_hilite/`) options if you've configured that as your highlighter, or it will use its own options if you've explicitly configured [`pymdownx.highlight`](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/).

Anyways, both `Codehilite` and `Highlight` use `Pygments` to do highlighting.  It is responsible for the output. `Pygments` has two line number output formats, `table` (which is the default) and `inline` where it just integrates the line numbers into the `pre` containing the code.  Each have their pros and cons. `table` allows for sane copy and paste and has bad line wrapping, while `inline` allows for wrapping but has bad copy and paste.

From Pygments' [documentation](http://pygments.org/docs/formatters/#HtmlFormatter):

> If set to 'table', output line numbers as a table with two cells, one containing the line numbers, the other the whole code. This is copy-and-paste-friendly, but may cause alignment problems with some browsers or fonts. If set to 'inline', the line numbers will be integrated in the `<pre>` tag that contains the code (that setting is new in Pygments 0.8).
>
> For compatibility with Pygments 0.7 and earlier, every true value except 'inline' means the same as 'table' (in particular, that means also True).
>
> The default value is False, which means no line numbers at all.
>
> Note: with the default (“table”) line number mechanism, the line numbers and code can have different line heights in Internet Explorer unless you give the enclosing `<pre>` tags an explicit line-height CSS property (you get the default line spacing with line-height: 125%).

Both `Codehilite` and `Highlight` use the `table` output, and are generally expected to use an overflow that allow scrolling instead of wrapping.

You are free to not use Pygments by disabling Pygments usage by setting the `use_pygments` option to `False` and instead configure a JavaScript highlighter that outputs in a format you like. When Pygments is **not** being used, the output of code blocks will be in the HTML format:

```html
<pre class="highlight"><code class="language-mylanguage"></code></pre>
```

If you have enabled `linenums`, all it will currently do is set a `linenums` class. We do not provide information like starting line numbers, step, etc.  This is because JavaScript highlighters all require different formats, there is no one, standard way, which makes it hard to provide a universal output.

```html
<pre class="highlight linenums"><code class="language-mylanguage"></code></pre>
```

**Comment by LennonChin** [comment]
Thank you for reply!

I have read related source code, and try to develop PostProcessor to process rendered result but the splitting points are hard to locate, It seem that this problem should be resolved by either standard codehilite extension or pygments' codehilite extension.

I would like to try to modify related source code of pygments to achieve the way use ul and li tags.

**Comment by facelessuser** [comment]
Pygments is its own repository.  Codehilte and Highlight both rely on it: https://bitbucket.org/birkenfeld/pygments-main.

You'd have to derive a new HTML formatter via Pygments API, and provide a way for SuperFences to use that formatter instead of what it uses now.

**Comment by facelessuser** [comment]
I feel this question has been answered. I have no current plans to implement a `ul`, `li` based `code` output.  I leave it up to the user to fork and experiment with such approaches.  If at a future time, we have a proof of concept that is compelling enough to have us reconsider, I'd be happy to have this issue reopened, or receive a pull request.

**Comment by LennonChin** [comment]
@facelessuser 

Hello,

I have expand the pygments' code line rendering, add a way use `ul` and `li` tags.

And I extended highlight lines' implements, now it can receive a json dict to render special styles for a special line.

Then I extended SuperFences to generate a control panel for code block, this control panel can be customed.

You can see my blog's example at this page [https://blog.coderap.com/article/4](https://blog.coderap.com/article/4) I will submit a PR to Pygments when it is being stabled

**Comment by facelessuser** [comment]
I'll be happy to evaluate your changes when you have a pull request.  I cannot promise what ultimately will be accepted, but I am open to evaluating proposals, and if accepted, willing to work with you to get it to a state we could merge.  Keep in mind that any new options should be optional as we have certain expectations out of the box for existing users.

**Comment by dbader** [comment]
> `table` allows for sane copy and paste and has bad line wrapping, while `inline` allows for wrapping but has bad copy and paste.

Just wanted to chime in here and say that I've had great success using the `inline` line numberer and marking the line number `<span>` elements as unselectable with the [`user-select` CSS property](https://css-tricks.com/almanac/properties/u/user-select/). Best of both worlds for my use case!

**Comment by facelessuser** [comment]
@dbader, I do have a branch with currently experimental line changes that does exactly that: https://github.com/facelessuser/pymdown-extensions/tree/linenums-experiment.  Just an FYI 😉 .

**Comment by dbader** [comment]
@facelessuser Haha cheers 😄
