### ISSUE TITLE
wrong result in arithmatex

### ISSUE THREAD

**Issue by Ir1d** [facelessuser/pymdown-extensions#432]
Hi, I was using arithmatex in mkdocs.
`$\text{asdfasdf $a_i$}$` results in two parts, while this is expected:

![image](https://user-images.githubusercontent.com/10709657/47967074-a999a300-e094-11e8-8060-7a1c563f2a0a.png)

upd: using latest version, with mathjax set up:

![image](https://user-images.githubusercontent.com/10709657/47967107-e4034000-e094-11e8-8d7c-d34f0d07e2fa.png)

**Comment by facelessuser** [comment]
What are you expecting to see?

**Comment by Ir1d** [comment]
I was expecting this: 
![image](https://user-images.githubusercontent.com/10709657/47967618-3abf4880-e09a-11e8-9785-f707b58d7810.png)

I noticed that some markdown editors support this while some not, so I guess this is not a bug but a feature request. :smile:

**Comment by facelessuser** [comment]
Why not use `\(\text{asdfasdf $a_i$}\)`?

**Comment by facelessuser** [comment]
This is basically a nested dollar issue. I don't even think turning off smart dollar would fix it. You have to use a non conflicting syntax. That is why I suggest an alternative syntax in this specific case.

I've recently added a way to do math in in fenced and inline code spans using custom fences or inline code spans (some setup required).

**Comment by facelessuser** [comment]
So looking into this more, there is a bit of complexity involved here if we wanted to support `\text{}` without requiring the user to swap out non-conflicting notation as technically this is valid (notice you can even swap the inline syntax between dollar and the alternative).

```
$\text{asdfasdf \(\text{$a_i$}\)}$
```

We couldn't just use a simple regular expression pattern (I mean we could, because I'm not sure I'd want to support the person who is doing massive chains of `\text{}` 🙂 ).  You could nest this forever swapping from text and back again. Additionally, while Arithmatex uses smart dollars on the outside, internally, that is all handled by MathJax or KaTeX. Internally, we'd have to parse with their relaxed logic.  Is this worth the effort?  I'm not sure.  Especially as you can just pick a syntax that doesn't conflict: `$\text{asdfasd \(a_i\)}$` or `\(\text{$a_i$}\)`.

Or even configure the new syntax and use this: `` `#!math \text{$a_i$}` `` or:

````
```math
\text{$a_i$}
```
````

**Comment by Ir1d** [comment]
Thx for your reply. :+1:  I didn't notice that `\(\text{asdfasdf $a_i$}\)` works.
