### ISSUE TITLE
[Question] Code blocks with language in list

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/pymdown-extensions#70]
### 1. Briefly

I don't find:

    how in Python Markdown I can get good convert code blocks,

        if:

            1. I have code block in lists,
            2. I have code block between some text,
            3. I have language for code.

### 2. Settings

For example, I have `test.md` file:

```markdown
1. First
1. Second

        ```python
        my Python code
        ```

    Text after second

1. Third
```

### 3. Steps to reproduce

I run in terminal:

```python
python -m markdown -x markdown.extensions.fenced_code test.md
```

### 4. Expected behavior

```html
<ol>
<li>First</li>
<li>
<p>Second</p>
<pre><code class="python">my Python code
</code></pre>
<p>Text after second</p>
</li>
<li>
<p>Third</p>
</li>
</ol>
```

### 5. Actual behavior

(By technical reasons I replace backticks to quotes — `'''`.)

```html
<ol>
<li>First</li>
<li>
<p>Second</p>
<pre><code>'''python
my Python code
'''
</code></pre>
<p>Text after second</p>
</li>
<li>
<p>Third</p>
</li>
</ol>
```

### 6. Did not help

1. [**This markup**](https://gist.github.com/clintel/1155906/71b2ab2e4444cb826b45f9988d067d1dd1edcc2c) works for me, if I indent code blocks, but doesn't work for me, if I write language for code block.
1. If I understood right, [**this not possible**](https://github.com/waylan/Python-Markdown/issues/53)e in Python Markdown 2.x versions.
1. I read your comment, but [**link in comment**](https://github.com/waylan/Python-Markdown/issues/53#issuecomment-57549877) is dead.
1. I don't find, how I can solve my problem, if I will use [**SuperFences**](http://facelessuser.github.io/pymdown-extensions/extensions/superfences/).

### 7. Do not offer

1. It would be nice, if would be possible solve the problem without pygments Python library. I use [**Rainbow.js**](https://craig.is/making/rainbows) for code blocks highlight → I think, using Rainbow.js better than pygments.

Thanks.

**Comment by facelessuser** [comment]
I am confused about a number of things.  But I will try and clarify some things.

1.  I don't know what version of pymdown-extensions you are using if any.  You should usually post that.

2. `markdown.extensions.fenced_code` does not support nested code blocks, SuperFences (`pymdownx.superfences`) does.  I do not support `markdown.extensions.fenced_code`  I support `pymdownx.superfences`.

2. SuperFences should be used **instead** of the Python Markdown "fenced_code".  SuperFences is meant to replace "fenced_code".

> It would be nice, if would be possible solve the problem without pygments Python library. I use Rainbow.js for code blocks highlight → I think, using Rainbow.js better than pygments.

I find this quite debatable, but I understand that people have different taste and requirements.  Pygments is never required though, but you will have to do a little extra work to use a JavaScript highlighter.

Recent versions I have started to navigate away from CodeHilite, but if you are using CodeHilite, you should disable `use_pygments` (I believe that is the setting), and if you use the `pymdownx.highlight`,  you should also disable `use_pygments`.

So you should get a pre code block with `language-mylanguage` applied to it:

````
```python
import test
```
````

```html
<pre class="highlight"><code class="language-python>import test</code></pre>
```
You will have to configure your JS highlighter to target the object and parse the language.  This may require you to write a JS script, or maybe it will handle it automatically.  As each JS highlight library may have different requirements, it is difficult to provide blocks that each library may recognize out of the box, so a script may be necessary to mitigate this.

**Comment by facelessuser** [comment]
Also, in your example, you over indented your code example.  You only need to indent by 4 not 8.

**Comment by Kristinita** [comment]
## 1. Replies

### 1. Version

> I don't know what version of pymdown-extensions you are using if any. You should usually post that.

1. I automatically update all my Python modules each week. I use last version — `pymdown-extensions==3.1`.
1. If my issue — is *question*, not *bugreport*, I doesn't write a version of my environment. Is it necessary?

### 2. SuperFences

> SuperFences should be used instead of the Python Markdown "fenced_code". SuperFences is meant to replace "fenced_code".

> markdown.extensions.fenced_code does not support nested code blocks, SuperFences (pymdownx.superfences) does. I do not support markdown.extensions.fenced_code I support pymdownx.superfences.

Yes, I know it. Thank you for reminding me.

### 3. pygments vs Rainbow.js

> I find this quite debatable, but I understand that people have different taste and requirements.

If pygments enable for me:

    example output:

```html
<div class="highlight"><pre><span></span><span class="err">WinActivate,</span> <span class="err">Mozilla</span> <span class="err">Firefox</span> <span class="err">ahk_class</span> <span class="err">MozillaWindowClass</span>
<span class="err">Sleep,</span> <span class="mi">300</span>
<span class="err">Send,</span> <span class="p">{</span><span class="err">Space</span><span class="p">}</span>
<span class="err">Sleep,</span> <span class="mi">300</span>
<span class="err">Send,</span> <span class="p">{</span><span class="err">LAlt</span> <span class="err">Down</span><span class="p">}</span>
```

Disadvantages:

1. I use [**Clipboard.js**](https://clipboardjs.com/) and [**Tooltipster**](https://iamceege.github.io/tooltipster/) JavaScript libraries — [**example**](http://kristinita.ru/Sublime-Text/SashaSublime#preferences). It depends on `<pre><code>` tags. I don't know, how I can set Tooltipster and Clipboard.js use pygments.
1. I don't like hundreds of `<span>` tags.

### 4. Set JavaScript parser

> You will have to configure your JS highlighter to target the object and parse the language.

I use Grunt plugin [**Text Replace**](https://github.com/yoniholmes/grunt-text-replace) for it, see [**part of my `Gruntfile.coffee`**](https://github.com/Kristinita/KristinitaPelican/blob/1d396ce8fbe8c03de9ade3c388c3e29624aa4c8a/Gruntfile.coffee#L67-L73) file.

### 5. Indentation

> Also, in your example, you over indented your code example. You only need to indent by 4 not 8 in lists.

I get same behavior as item 5 of my first post for superfences and default fenced_code extensions.

---

## 2. Question

I'm sorry, can you write real example, how I can get expected behavior from item 4 of my first post?

Thanks.

**Comment by facelessuser** [comment]
> If my issue — is question, not bugreport, I doesn't write a version of my environment. Is it necessary?

It's probably always a good idea to post version of software you use so that when I give advice, I know if it will work on the particular version you are using.

> I don't like hundreds of <span> tags.

No matter what highlighter you use, there will be hundreds of spans.  Either they will be there before, like Pygments does by pre-rendering them which requires you loading no additional JavaScript, or it will be after like Rainbow.js does which requires more HTML requests to load more JavaScript.  

This is actual Rainbow.js output after conversion (in the browser, not source text); there are spans.  I got this simply by inspecting with my browser their home page example.  It's basically the same, it's just JavaScript libraries convert it in your browser, and Pygments does it before directly in the source.

```html
<pre data-trimmed="true" class=""><code data-language="javascript" data-delay="3" class="rainbow"><span class="comment">/*
 * This is some sample code to illustrate how things look!
 */</span>
<span class="keyword">import</span> Musician <span class="keyword">from</span> <span class="string">'./liverpool'</span>;

<span class="storage type class">class</span> <span class="entity name class">Paul</span> <span class="storage modifier extends">extends</span> <span class="entity other inherited-class">Musician</span> {
    <span class="entity name function">constructor</span>(bass) {
        <span class="variable language super">super</span>(bass);
    }

    <span class="storage type accessor">get</span> <span class="entity name function">fullName</span>() {
        <span class="keyword">return</span> <span class="string">'Paul McCartney'</span>;
    }

    <span class="entity name function">perform</span>() {
        <span class="variable language this">this</span>.<span class="function call">play</span>(<span class="variable language this">this</span>.instrument);
        <span class="variable language this">this</span>.<span class="function call">sing</span>();
    }
}

<span class="keyword">export</span> <span class="keyword">default</span> Paul;</code><div class="preloader"><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div></pre>
```

Again, all I'm saying is people have different needs, I'm not trying to say you *should* use Pygments, just that there are pros and cons both ways.

> I use Clipboard.js and Tooltipster JavaScript libraries — example. It depends on <pre><code> tags. I don't know, how I can set Tooltipster and Clipboard.js use pygments.

I don't see why these can't be used with Pygments, but it is fine if you don't want to do Pygments.  It looks like you are just applying tooltips to your clipboard buttons which has nothing to do with how the code is styled.  From what I understand, clipboard could be applied to `<div><pre>` but I haven't played with it before.

Unfortunately, I just provide some extensions to format Markdown output, I don't provide support for figuring out how to incorporate various different JS libraries into web pages.  If it is something I have done before, I don't usually mind pointing people at examples, but I don't have time to solve people's web design issues.  I do think the Clipboard.js library looks interesting. 

I feel that a JS script could be written to target Pygments `<div><pre>` blocks and generate unique ids for each and insert a clipboard button that points to those targets.  I don't think it would be too hard.

---

> I'm sorry, can you write real example, how I can get expected behavior from item 4 of my first post?

First, there are two kinds of code blocks: standard Markdown indented code blocks, and then fenced blocks.

````
    ```
    some code
    ```
````

Which gives you 

    ```
    some code
    ```

Notice the whole fences are indented, so they are counted as code.

Now you have fenced:

````
```
some code
```
````

And you get

```
some code
```

Notice the fences this time are counted as tokens for highlighting.  This is why I am saying you are indenting your code to much in your example.  But when you deindent you don't get a fence block because **only** superfences will provide highlighting on a fence nested under a list.

So here is your example with fixed indentation.

```
1. First
1. Second

    ```python
    my Python code
    ```

    Text after second

1. Third
```

Here is a config file to send parameters to the extensions.  You could just as easily replace `pymdownx.highlight` with `markdown.extensions.codehilite`, but in this example, we will use `highlight`.

```js
{
    "pymdownx.highlight": {
        "use_pygments": false
    }
}
```

Command line:

```
python -m markdown -x pymdownx.superfences -x pymdownx.highlight -c extension.json test.md
```

Output:

```html
<ol>
<li>First</li>
<li>
<p>Second</p>
<pre class="highlight"><code class="language-python">my Python code</code></pre>


<p>Text after second</p>
</li>
<li>
<p>Third</p>
</li>
</ol>
```

That's how you get no Pygments and nested highlighting.  I am aware of the excessive whitespace after the code block.  It's harmless, but it will be taken care of in a future version.

**Comment by facelessuser** [comment]
Clipboard.js can work with Pygments. Here is a quick example I threw together as an example for the mkdocs-material theme: https://github.com/squidfunk/mkdocs-material/issues/315#issuecomment-300027498.

There is no need to use Pygments as I showed in previous posts that SuperFences can output a format without Pygments, but this shows you can go either way.

**Comment by facelessuser** [comment]
I'm going to go ahead and close this as I feel the question has been answered, but if you still have more questions, feel free to ask.
