### ISSUE TITLE
Inline $...$ Equations with Mathjax3

### ISSUE THREAD

**Issue by rapon233** [facelessuser/pymdown-extensions#842]
[Originnal Post](https://github.com/squidfunk/mkdocs-material/issues/1481#issue-575110404)

I creat a new [repo](https://github.com/rapon233/mathjaxtest/blob/master/docs/index.md) for test.
As you see, https://rapon233.github.io/mathjaxtest/
Inline $...$ equation could not render as expected. And 2.7.0 works fine.
Anything wrong with the docs？

**Comment by facelessuser** [comment]
@rapon233 I am using `$...$` in Arithmatex source. Please look at the very first inline example: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#input-format.

It is being rendered using `$...$` as shown in the example and is using MathJax 3. This is the exact setup I am using: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/markdown/_snippets/mathjax.txt. You can see on this line that I am truly using MathJax 3: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/markdown/_snippets/mathjax.txt#L33.

---

With that said, I also looked at your repo, and you had a number of issues:

1. A broken config. Brackets were not matching up proper.
2. You were double escaping some brackets `\\[...\\]`. This is a good indicator that you don't have things setup proper. Arithmatex does not require you to double escape brackets. The documentation clearly shows the syntax to be `\[...\]` and `\(...\)`, no double escaping necessary. See: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#input-format.
3. Blocks should be in their own paragraph. See: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#input-format.

Anyways, here is a diff that fixes things:

```diff
diff --git a/docs/index.md b/docs/index.md
index 5a703f4..d109798 100644
--- a/docs/index.md
+++ b/docs/index.md
@@ -1,8 +1,13 @@
 # Test For Render
 
-Inline1:$\Delta$    
-Inline2:\\(\Delta\\)    
-Block1   
-$$ \Delta $$    
-Block2   
-\\[\Delta\\]
+Inline1: $\Delta$
+
+Inline2: \(\Delta\)
+
+Block1
+
+$$ \Delta $$
+
+Block2
+
+\[\Delta\]
diff --git a/docs/js/test.js b/docs/js/test.js
index df8b8ed..04a38e2 100644
--- a/docs/js/test.js
+++ b/docs/js/test.js
@@ -6,9 +6,9 @@ window.MathJax = {
       tagIndent: ".8em",
       multlineWidth: "85%",
       tags: "ams",
-      autoload: expandable({
-        mhchem: ['ce', 'pu']
-      }
+      // autoload: expandable({
+      //   mhchem: ['ce', 'pu']
+      // }
     },
     options: {
       ignoreHtmlClass: 'tex2jax_ignore',
@@ -27,7 +27,8 @@ window.MathJax = {
             if (sibling && sibling.matches('.MathJax_Preview')) {
               sibling.parentNode.removeChild(sibling);
             }
-        }, '']
+        }
+      }, '']
     }
   }
-};
\ No newline at end of file
+};
```

Also:

![chrome_g2Z9bRB5ym](https://user-images.githubusercontent.com/1055125/76176328-d6246a00-6175-11ea-8f4a-c0fab2ab89a3.png)




because your config was broken and they weren't passing through proper.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: support

**Comment by rapon233** [comment]
Thanks for the explanation. 
In md writing, I used to add a `Tab`(or blank spaces`    `) at the end of a line as break, instead of a blank line.
It worked well in VScode and previous mathjax version.
Seems I need to convert to another expression.

**Comment by facelessuser** [comment]
Spaces can force a line break inside a paragraph, but it doesn't start a new block.

**Comment by facelessuser** [comment]
Block style must be in it's own block. Using spaces for line breaks while using inline style should be fine.
