### ISSUE TITLE
PathConverter not working as expected

### ISSUE THREAD

**Issue by raphaelyancey** [facelessuser/pymdown-extensions#875]
Live example: https://repl.it/repls/DizzyFickleCallback

```python
import markdown

raw = '[README.md](README.md)\n\n[./README.md](./README.md)\n'

a = markdown.markdown(raw,
                      extensions=['pymdownx.pathconverter'],
                      extensions_configs={
                        'pymdownx.pathconverter': {
                          'absolute': True,
                          'base_path': 'http://github.com',
                        }
                      })

print(a)

# Returns:
# <p><a href="README.md">README.md</a></p>
# <p><a href="./README.md">./README.md</a></p>
```

I'd like the relatives links to have `http://github.com` as a base URL (example). Am I using this correctly?

**Comment by facelessuser** [comment]
Your problem is that you are specifying one of your parameter names incorrectly, particularly `extensions_configs` which should be `extension_configs`. This is what I get once I correct this:

```py
<p><a href="/http%3A/github.com/README.md">README.md</a></p>
<p><a href="/http%3A/github.com/README.md">./README.md</a></p>
```

So works as expected, but maybe not for you as I can see that you are  using a URL as `base_path` instead of a local path. We can see sense I'm running this on Linux, that it is escaping things like`:` and also normalizing `//` to `/`. This is because the extension, in  its current form expects that it is working with file paths, not URLs. Additionally it adds a leading `/` if one is omitting on absolute paths to ensure the pats work on Chrome and Firefox, because Firefox won't load a path `c:/my-folder/my-file` without seeing it as `/c:/my-folder/my-file`. You can view the current tests to see the behavior: https://github.com/facelessuser/pymdown-extensions/blob/master/tests/test_extensions/test_pathconverter.py#L260.

It is helpful to maybe read the documentations opening statement:

> PathConverter is an extension that can convert local, relative reference paths to absolute or relative paths for links and images. It was originally written for a project that wanted to preview the markdown by rendering it in a temporary location. This extension allowed the paths to be converted to work from the temporary location. This context is important when trying to understand why this extension was created. It's actual usage is limited to situations like this, so it isn't something that would get used in most normal scenarios.

I think that helps to clarify why I originally wrote it, and why its behavior is as noted above. To take it in a different direction, I would need a feature proposal. I do not wish to lose current functionality as I do use it in other projects. If we wanted a URL mode, we'd have to add the appropriate options and logic. I am open to suggestions and pull requests, though neither guarantees I will adopt the change, but it can at least start a conversation. 

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by raphaelyancey** [comment]
Alright, thanks for the details. I missed that, and the typo :)

I'll make a PR if I have extra time. For information, my use case is the following: my web app fetches READMEs from remote repositories and displays them. Thus, relative links needs to be changed to absolute URLs pointing to the repo.

**Comment by facelessuser** [comment]
Understood, your use case is a bit different than my original. While a perfectly valid use case, not one that I have yet had a need for, hence the lack of such functionality here. Almost all of the extensions here are born from selfish needs on my part, so they are tailored to specific use cases I was  trying to solve. Some are clearly more helpful to the general audience than others 🙂.
