### ISSUE TITLE
Incorrect calculation of reference links when using snippets

### ISSUE THREAD

**Issue by steve-todorov** [facelessuser/pymdown-extensions#881]
### Bug report (maybe feature request?)

[Reference links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) are incorrectly calculated when you include a snippet into another markdown document.

### Use case

When you have a markdown documentation which grows it quickly becomes annoying to have to write down the same links over and over. It becomes even more annoying to have to fix the links when they change across all pages involved. It would be great if it is possible to have common links stored in a sort of "meta" markdown page which you can import into another page and reference the common links.

### Steps to reproduce

* [Strongbox Docs](https://github.com/strongbox/strongbox-docs) (example repo)
* Add a file called `global-link-references.md` under `docs` with the following content:

    ```
    [<!-- Global links which can be shared across all pages such as links to JDK8, system requirements, etc -->]: # 
    [<!-- Strongbox related links -->]: # 
    [strongbox-distribution-setup]: ./user-guide/getting-started.md <--- this path is relative to `global-link-references.md`, but will be incorrectly rendered later
    ```
* Change any file in a sub-dir like `./docs/user-guide/tool-integration/gradle.md` and include this at the very beginning: 
    ```
    --8<-- "global-link-references.md"
    ```
  * Add a reference link in the same document i.e. `[My Strongbox Distribution Reference Link][strongbox-distribution-setup]`
* `docker run -it --rm -v /path/to/strongbox-docs-clone:/docs -p 8000:8000 strongboxci/mkdocs:base serve -v -a 0.0.0.0:8000`
* Go to `http://localhost:8000/user-guide/tool-integration/gradle-example.html`
* The link `My Strongbox Distribution Reference Link` will point to 
    ```
    http://localhost:8000/user-guide/tool-integration/user-guide/getting-started.md
    ```
    instead of 
    ```
    http://localhost:8000/user-guide/getting-started.html
    ```

**Comment by facelessuser** [comment]
From what I understand, this is working fine for external links, but specifically you have an issue with it working with relative, internal links?

If so, this is completely expected behavior and is not a bug. Snippets takes content from one file, and inserts it into another, that's it. There is no pre-parsing of the data to determine context of content.

This appears to be a mkdocs question really, you can try using absolute links (and dropping the extension so as not to trigger mkdocs url augmentation): `/user-guide/getting-started/`. You could also probably write your own mkdocs plugin and figure out how to handle this, or you could use the full, actual link that the deployed docs will use `https://somesite.com/user-guide/getting-started`. There may be other approaches, like with a Python Markdown extension.

With all of that said, I think your request is out of scope for snippets.

@gir-bot remove S: triage
@gir-bot add T: feature, S: wontfix

**Comment by steve-todorov** [comment]
Yeah, it's specifically related to the internal links. Thanks for the input - I'll be closing this then! :)
